import HistoryTabs from "@/components/history-tabs";
import ConsolidatedOrdersTable from "@/components/consolidated-orders-table";
import { DataTable, ViewSection } from "@/components/operational-views";
import PageHeading from "@/components/page-heading";
import { loadDashboardData } from "@/lib/dashboard-data";

export default async function OperationsPage() {
  const data = await loadDashboardData();
  const signalRows = data.signals.slice(0, 30).map((row) => [String(row.created_at ?? "-").slice(11, 16), String(row.symbol ?? "-"), String(row.direction ?? "-"), String(row.score ?? "-"), String(row.strategy ?? "-"), String(row.status ?? "-")]);
  const tradeRows = data.trades.slice(0, 30).map((row) => [String(row.symbol ?? "-"), String(row.direction ?? "-"), String(row.entry_price ?? "-"), String(row.exit_price ?? "-"), String(row.pnl ?? "-"), String(row.status ?? "-")]);
  return <div className="space-y-4 p-3 sm:p-4 lg:p-5"><PageHeading title="Operaciones" description="Sigue el estado actual reportado por el broker, cancela órdenes todavía activas y consulta el historial de ejecuciones confirmadas, posiciones y operaciones locales." /><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Órdenes persistidas", data.operationalOrders.length, "Historial trazable creado desde ALFA-OMEGA."], ["Órdenes en curso", data.brokerRows.length, "Se pueden cancelar mientras el broker las mantenga activas."], ["Ejecuciones confirmadas", data.executionRows.length, "Historial devuelto por el broker para la sesión disponible."], ["Posiciones abiertas", data.positionRows.length, "Exposición actual y PnL reportado por el broker."]].map(([label, value, help]) => <article key={String(label)} className="rounded-md border border-sky-400/15 bg-[#07111f] p-4"><p className="text-xs text-slate-500">{String(label)}</p><p className="mt-1 text-2xl font-bold text-sky-100">{String(value)}</p><p className="mt-2 text-[11px] leading-4 text-slate-500">{String(help)}</p></article>)}</section><ViewSection title="Historial consolidado" description="Órdenes creadas desde ALFA-OMEGA con su ID local, ID del broker, origen y estado normalizado. La cancelación usa el ID local y espera confirmación del broker."><ConsolidatedOrdersTable rows={data.operationalOrders} /></ViewSection><HistoryTabs brokerRows={data.brokerRows} executionRows={data.executionRows} positionRows={data.positionRows} signalRows={signalRows} tradeRows={tradeRows} /><ViewSection title="Operaciones locales" description="Estas operaciones pertenecen al registro local. Una orden enviada al broker solo se considera ejecutada cuando aparece confirmada en Historial broker."><DataTable rows={data.trades} columns={[["symbol", "Instrumento"], ["direction", "Dirección"], ["entry_price", "Entrada"], ["exit_price", "Salida"], ["pnl", "PnL"], ["status", "Estado"]]} /></ViewSection></div>;
}
