ALTER TABLE trades
  ADD COLUMN IF NOT EXISTS stop_loss NUMERIC,
  ADD COLUMN IF NOT EXISTS take_profit_1 NUMERIC,
  ADD COLUMN IF NOT EXISTS take_profit_2 NUMERIC;

CREATE TABLE IF NOT EXISTS market_prices (
  symbol TEXT PRIMARY KEY,
  price NUMERIC NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
